import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:fluttertoast/fluttertoast.dart';

class TutorialPage extends StatelessWidget {
  const TutorialPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Usage App',
          style: GoogleFonts.aBeeZee(
            color: Colors.white,
            letterSpacing: 1,
            fontWeight: FontWeight.bold,
          ),
        ),
        backgroundColor: HexColor('#D4246F'),
        elevation: 0.3,
        centerTitle: true,
        leadingWidth: 60,
        leading: Center(),
      ),
      body: Container(
        color: Colors.white12,
        child: TutorialSlides(),
      ),
    );
  }
}

class TutorialSlides extends StatefulWidget {
  @override
  _TutorialSlidesState createState() => _TutorialSlidesState();
}

class _TutorialSlidesState extends State<TutorialSlides> {
  final PageController _pageController = PageController();

  List<Widget> buildSlides() {
    return [
      TutorialSlide(
        title: 'Welcome to Crowd Counting App',
        description: 'Learn how to use the app to count crowds with precision.',
        image: 'assets/images/homescreen.jpeg',
        pageController: _pageController,
        totalSlides: 4,
      ),
      TutorialSlide(
        title: 'Capture Images',
        description:
            'Use the camera to capture images or pick from the gallery.',
        image: 'assets/images/pickfrom.jpeg',
        pageController: _pageController,
        totalSlides: 4,
      ),
      TutorialSlide(
        title: 'Correct Way Capture (Example)',
        description:
            'The picture should be like this because the app correct counting based of head annotation',
        image: 'assets/images/crowd_image.jpeg',
        pageController: _pageController,
        totalSlides: 4,
      ),
      TutorialSlide(
        title: 'View Prediction Result',
        description:
            'Explore accurate crowd count predictions generated by the app.',
        image: 'assets/images/result_page.jpeg',
        pageController: _pageController,
        totalSlides: 4,
      ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return PageView.builder(
      controller: _pageController,
      physics: NeverScrollableScrollPhysics(),
      itemCount: buildSlides().length,
      itemBuilder: (context, index) {
        return buildSlides()[index];
      },
    );
  }
}

class TutorialSlide extends StatelessWidget {
  final String title;
  final String description;
  final String image;
  final PageController pageController;
  final int totalSlides;

  TutorialSlide({
    required this.title,
    required this.description,
    required this.image,
    required this.pageController,
    required this.totalSlides,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: EdgeInsets.all(16.0),
      elevation: 5.0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(15.0),
      ),
      child: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            colors: [Colors.black12, Colors.black12],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
          borderRadius: BorderRadius.circular(15.0),
          boxShadow: [
            BoxShadow(
              color: Colors.white.withOpacity(0.1),
              spreadRadius: 2,
              blurRadius: 7,
              offset: Offset(0, 3),
            ),
          ],
        ),
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Image.asset(
                image,
                height: 400,
              ),
              SizedBox(height: 16),
              Text(
                title,
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.black,
                ),
                textAlign: TextAlign.center,
              ),
              SizedBox(height: 7),
              Text(
                description,
                style: TextStyle(
                  fontSize: 18,
                  color: Colors.black,
                ),
                textAlign: TextAlign.center,
              ),
              SizedBox(height: 16),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      Navigator.of(context).pop();
                      Fluttertoast.showToast(
                        msg: 'Back to home screen.',
                        toastLength: Toast.LENGTH_SHORT,
                        gravity: ToastGravity.CENTER,
                        timeInSecForIosWeb: 1,
                        backgroundColor: Colors.grey,
                        textColor: Colors.black,
                        fontSize: 20.0,
                      );
                    },
                    child: Text(
                      '      Skip     ',
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    style: ElevatedButton.styleFrom(
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                        side: BorderSide(
                          color: HexColor('#D4246F'),
                          width: 1.0,
                        ),
                      ),
                      elevation: 5,
                      backgroundColor: HexColor('#D4246F'),
                      padding: EdgeInsets.all(8),
                    ),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      if (pageController.page! < totalSlides - 1) {
                        // Navigate to the next slide
                        pageController.nextPage(
                          duration: Duration(milliseconds: 500),
                          curve: Curves.ease,
                        );
                      } else {
                        pageController.jumpToPage(0);
                        // Show a toast message
                        Fluttertoast.showToast(
                          msg: 'You reached the end. Starting again.',
                          toastLength: Toast.LENGTH_SHORT,
                          gravity: ToastGravity.CENTER,
                          timeInSecForIosWeb: 1,
                          backgroundColor: Colors.grey,
                          textColor: Colors.black,
                          fontSize: 20.0,
                        );
                      }
                    },
                    child: Text(
                      'Next Step',
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    style: ElevatedButton.styleFrom(
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                        side: BorderSide(
                          color: HexColor('#D4246F'),
                          width: 1.0,
                        ),
                      ),
                      elevation: 5,
                      backgroundColor: HexColor('#D4246F'),
                      padding: EdgeInsets.all(8),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
